name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21' 

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: make lint

    - name: Run tests
      run: npm run test

    - name: Upload coverage to CodeClimate
      run: |
        npm install -g codeclimate-test-reporter
        codeclimate-test-reporter < lcov.info
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
